wordpress:
  image: wordpress
  links:
    - db:mysql
  ports:
    - 8080:80
  volumes:
    - .:/var/www/html/wp-content/themes/mla-style-center

db:
  image: mariadb
  environment:
    MYSQL_ROOT_PASSWORD: example
